# Generated by Django 3.0.7 on 2024-05-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200625_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='facebook_link',
            new_name='github_link',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='google_plus_link',
            new_name='linkedin_link',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='twitter_link',
            new_name='portfolio_link',
        ),
    ]
