# Generated by Django 3.0.7 on 2024-05-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20240508_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('BAR', 'Baringo'), ('BOM', 'Bomet'), ('BUN', 'Bungoma'), ('BUS', 'Busia'), ('EAS', 'East Pokot'), ('ELG', 'Elgeyo Marakwet'), ('EMB', 'Embu'), ('GAR', 'Garissa'), ('HOM', 'Homa Bay'), ('ISR', 'Isiolo'), ('KAJ', 'Kajiado'), ('KAK', 'Kakamega'), ('KIL', 'Kilifi'), ('KIR', 'Kirinyaga'), ('KIS', 'Kisii'), ('KIT', 'Kitui'), ('KWA', 'Kwale'), ('LAI', 'Laikipia'), ('LAM', 'Lamu'), ('MBA', 'Machakos'), ('MAK', 'Makueni'), ('MAN', 'Mandera'), ('MER', 'Meru'), ('MIG', 'Migori'), ('MUR', "Murang'a"), ('NAR', 'Nairobi'), ('NAK', 'Nakuru'), ('NAN', 'Nandi'), ('NAR', 'Narok'), ('NYA', 'Nyamira'), ('NYA', 'Nyandarua'), ('NYE', 'Nyeri'), ('SAM', 'Samburu'), ('SIY', 'Siaya'), ('TAI', 'Taita-Taveta'), ('TAN', 'Tana River'), ('THA', 'Tharaka-Nithi'), ('TUR', 'Trans Nzoia'), ('TUR', 'Turkana'), ('UAS', 'Uasin Gishu'), ('VIH', 'Vihiga'), ('WAJ', 'Wajir'), ('WES', 'West Pokot')], max_length=100),
        ),
    ]
